language: ruby

notifications:
  email: false

rvm:
  - 2.2.2 # deployed
  - 2.3.1

sudo: false
cache: bundler
env:
  - ROBOT_ENVIRONMENT=local

before_script: 
  - test -d log || mkdir log
  - test -d run || mkdir run
