language: ruby

notifications:
  email: false

rvm:
  - 2.5.3
  - 2.7.1

before_install:
  - gem update --system

sudo: false
cache: bundler
env:
  - ROBOT_ENVIRONMENT=test

before_script:
  - test -d log || mkdir log
  - test -d run || mkdir run
