- dor_gisAssemblyWF_approve-data
- dor_gisAssemblyWF_approve-metadata
- dor_gisAssemblyWF_assign-placenames
- dor_gisAssemblyWF_author-metadata
- dor_gisAssemblyWF_extract-boundingbox
- dor_gisAssemblyWF_extract-iso19139
- dor_gisAssemblyWF_extract-thumbnail
- dor_gisAssemblyWF_finish-data
- dor_gisAssemblyWF_finish-gis-assembly-workflow
- dor_gisAssemblyWF_finish-metadata
- dor_gisAssemblyWF_generate-content-metadata
- dor_gisAssemblyWF_generate-geo-metadata
- dor_gisAssemblyWF_generate-mods
- dor_gisAssemblyWF_load-geo-metadata
- dor_gisAssemblyWF_normalize-data
- dor_gisAssemblyWF_package-data
- dor_gisAssemblyWF_start-assembly-workflow
- dor_gisAssemblyWF_start-delivery-workflow
- dor_gisAssemblyWF_wrangle-data
- dor_gisDeliveryWF_finish-gis-delivery-workflow
- dor_gisDeliveryWF_load-geoserver
- dor_gisDeliveryWF_load-geowebcache
- dor_gisDeliveryWF_load-raster
- dor_gisDeliveryWF_load-vector
- dor_gisDeliveryWF_seed-geowebcache
- dor_gisDeliveryWF_start-gis-discovery-workflow
- dor_gisDiscoveryWF_export-opengeometadata
- dor_gisDiscoveryWF_finish-gis-discovery-workflow
- dor_gisDiscoveryWF_generate-geoblacklight
- dor_gisDiscoveryWF_load-geoblacklight